services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - app-network

  backend:
    image: ghcr.io/barbarastep/film-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      LOGGER_TYPE: ${LOGGER_TYPE}
      PORT: ${PORT}
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: ghcr.io/barbarastep/film-frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    volumes:
      - frontend_dist:/dist
    depends_on:
      - backend
    networks:
      - app-network
    command: ["sh", "-c", "cp -r /app/dist/. /dist && tail -f /dev/null"]

  nginx:
    image: ghcr.io/barbarastep/film-nginx:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_dist:
  postgres_data:
  pgadmin_data:
